site_name: apex-fin
theme:
  name: material
  palette:
    - scheme: slate
      primary: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    logo: material/robot

watch: [mkdocs.yml, src/apex_fin]

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: true
            merge_init_into_class: true
          paths: [src]
  - mermaid2
  - minify
  - literate-nav

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


nav:
  - Introduction: index.md
  - Overview: overview.md
  - Installation: installation.md
  - How-To Guide: how_to.md
  - Sample Reports:
      - BYDD Gemini Flash 2.0: sample_reports/example_report_BYDD_gemini_flash_2_0.md
      - BYDD Gemini Flash 2.5: sample_reports/example_report_BYDD_gemini_flash_2_5.md
  - Configuration: configuration.md
  - Customizing Prompts: prompts_customization.md
  - Data: data_fetching.md
  - API:
      - Overview: api.md
      - Reference:
          - Agents: reference/apex_fin/agents/index.md
          - Models: reference/apex_fin/models/index.md
          - Teams: reference/apex_fin/teams/index.md
          - Prompts: reference/apex_fin/prompts/index.md
          - Templates: reference/apex_fin/templates/index.md
          - Utils: reference/apex_fin/utils/index.md
