name: Build Documentation

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        pip install uv

    - name: Install dependencies
      run: |
        uv sync --only-dev

    - name: Build documentation
      run: |
        mkdocs build

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add site/
        git commit -m "Deploy documentation to GitHub Pages"
        git push origin HEAD:gh-pages --force